<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.735" tests="56" errors="52" skipped="4" failures="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.91-b14"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/aluno/spring-projects/maven/spring-data-redis"/>
    <property name="java.runtime.version" value="1.8.0_91-b14"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-91-generic"/>
    <property name="user.home" value="/home/aluno"/>
    <property name="user.timezone" value="America/Fortaleza"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="aluno"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="pt"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_91"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="testCompareSet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <skipped message="DATAREDIS-108 Test is intermittently failing"/>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoValueSerializer[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.004">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testShouldBeAbleToUseRedisAtomicIntegerWithProperlyConfiguredRedisTemplate[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndIncrement[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testIncrementAndGet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="getThrowsExceptionWhenKeyHasBeenRemoved[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testCheckAndSet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoKeySerializer[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testAddAndGet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="getAndSetReturnsZeroWhenKeyHasBeenRemoved[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testDecrementAndGet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndAdd[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndSet[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndDecrement[0]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testCompareSet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <skipped message="DATAREDIS-108 Test is intermittently failing"/>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoValueSerializer[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488501 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488506 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@645482568
01475611488507 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testShouldBeAbleToUseRedisAtomicIntegerWithProperlyConfiguredRedisTemplate[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488509 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488510 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1073763441
01475611488510 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetAndIncrement[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488512 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488513 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@914356853
01475611488513 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testIncrementAndGet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488515 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488515 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1229161065
01475611488515 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="getThrowsExceptionWhenKeyHasBeenRemoved[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488517 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488518 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@195228908
01475611488518 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testCheckAndSet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488519 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488520 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@471579726
01475611488520 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoKeySerializer[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488522 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488522 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1442726378
01475611488522 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testAddAndGet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488524 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488524 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@16503286
01475611488524 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="getAndSetReturnsZeroWhenKeyHasBeenRemoved[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488526 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488526 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@484589713
01475611488526 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testDecrementAndGet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488528 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488528 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1574598287
01475611488528 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetAndAdd[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488530 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488530 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@2056031695
01475611488530 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetAndSet[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488532 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488532 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@606508809
01475611488532 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetAndDecrement[1]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException"><![CDATA[org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
    <system-err><![CDATA[01475611488534 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611488534 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@718187988
01475611488534 Tue Oct 04 17:04:48 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testCompareSet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <skipped message="DATAREDIS-108 Test is intermittently failing"/>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoValueSerializer[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testShouldBeAbleToUseRedisAtomicIntegerWithProperlyConfiguredRedisTemplate[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testGetAndIncrement[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testIncrementAndGet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="getThrowsExceptionWhenKeyHasBeenRemoved[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testCheckAndSet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoKeySerializer[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testAddAndGet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="getAndSetReturnsZeroWhenKeyHasBeenRemoved[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.002">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testDecrementAndGet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testGetAndAdd[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testGetAndSet[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testGetAndDecrement[2]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
]]></error>
  </testcase>
  <testcase name="testCompareSet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <skipped message="DATAREDIS-108 Test is intermittently failing"/>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoValueSerializer[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testShouldBeAbleToUseRedisAtomicIntegerWithProperlyConfiguredRedisTemplate[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndIncrement[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testIncrementAndGet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="getThrowsExceptionWhenKeyHasBeenRemoved[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testCheckAndSet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testShouldThrowExceptionIfRedisAtomicIntegerIsUsedWithRedisTemplateAndNoKeySerializer[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testAddAndGet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="getAndSetReturnsZeroWhenKeyHasBeenRemoved[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testDecrementAndGet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0.001">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndAdd[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndSet[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
  <testcase name="testGetAndDecrement[3]" classname="org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests" time="0">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException"><![CDATA[org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.support.atomic.RedisAtomicIntegerTests.<init>(RedisAtomicIntegerTests.java:60)
]]></error>
  </testcase>
</testsuite>