<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.572" tests="16" errors="14" skipped="2" failures="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.91-b14"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/aluno/spring-projects/maven/spring-data-redis"/>
    <property name="java.runtime.version" value="1.8.0_91-b14"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-91-generic"/>
    <property name="user.home" value="/home/aluno"/>
    <property name="user.timezone" value="America/Fortaleza"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="aluno"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="pt"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_91"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="testValidateNoError" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.436">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="factoryWorksWithoutClientResources" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.006">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testConnectWithPassword" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0">
    <skipped message="Redis must have requirepass set to run this test"/>
  </testcase>
  <testcase name="testInitConnection" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.005">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testGetSharedConnectionNotShared" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.005">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testLotsOfConnections" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0">
    <skipped message="Uncomment this test to manually check connection reuse in a pool scenario"/>
  </testcase>
  <testcase name="testDisableSharedConnection" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.005">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testResetConnection" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.007">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testGetNewConnectionOnError" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.01">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testGetConnectionException" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.009">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testConnectionErrorNoValidate" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.006">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="dbIndexShouldBePropagatedCorrectly" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.002">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testCreateFactoryWithPool" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.002">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testGetConnectionNotSharedBadHostname" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testSelectDb" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.002">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
  <testcase name="testResetAndInitConnection" classname="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests" time="0.001">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactoryTests.setUp(LettuceConnectionFactoryTests.java:60)
Caused by: java.net.ConnectException: Conex達o recusada: /127.0.0.1:6379
</error>
  </testcase>
</testsuite>